### ISSUE TITLE
Mina kurser, horisontell scrollbar

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#17]
På min chrome/Windows dyker en horisontell scrollbar upp. Förslag till lösning:

Ändra CSS för klassen program__intro:
```css
.program__intro {
    width: 100%;
    ...
}
```
